apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    {{- range $key, $value := .Values.app.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  type: {{ .Values.app.serviceType | quote }}
  ports:
  - port: {{ .Values.app.servicePort }}
    targetPort: {{ .Values.app.container.port }}
    protocol: {{ .Values.app.serviceProtocol | quote }}
    nodePort: {{ .Values.app.serviceNodePort }}
