apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
  {{- if .Values.dbPersistentVolume.labels }}
  labels:
    {{- range $key, $value := .Values.dbPersistentVolume.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.dbPersistentVolume.capacity | quote }}
  storageClassName: {{ .Values.dbPersistentVolume.storageClassName | quote }}
  accessModes:
    {{- range .Values.dbPersistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ .Values.dbPersistentVolume.hostPath | quote }}
