apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-db-service
spec:
  selector:
    {{- range $key, $value := .Values.db.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  ports:
  - port: {{ .Values.db.servicePort }}
    targetPort: {{ .Values.db.container.port }}
