version: "3.8"

services:

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.6
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
