apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: 
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template: # Pod Specification
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: container-my-app
          image: josejnra/my-app:1.2.2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: # ConfigMap
                  name: db-configmap
                  key: db-service
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef: # ConfigMap
                  name: db-configmap
                  key: db-database
            - name: DB_USER
              valueFrom:
                secretKeyRef: # Secret
                  name: db-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: # Secret
                  name: db-secrets
                  key: db-user-password
          resources:
            limits:
              memory: 1G
              cpu: "0.5"
