version : '3.8'
services:

  mysql:
    image: mysql:5.7.33
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "example"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
