apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: 
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: container-my-app
          image: josejnra/my-app:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: app-db-service
          resources:
            limits:
              memory: 1G
              cpu: "0.5"
