apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-deployment
  labels: 
    app: my-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: container-my-app-db
          image: josejnra/my-app-db:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-user-password
          volumeMounts:
            - name: db-volume-mount
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: 1G
              cpu: "0.5"
      volumes:
        - name: db-volume-mount
          persistentVolumeClaim:
            claimName: db-pvc
