apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-deployment
  labels: 
    app: my-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: container-my-app-db
          image: josejnra/my-app-db:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
          resources:
            limits:
              memory: 1G
              cpu: "0.5"
