apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: 
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template: # Pod Specification
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - app
              topologyKey: kubernetes.io/hostname
      containers:
        - name: container-my-app
          image: josejnra/my-app:1.2.2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: # ConfigMap
                  name: db-configmap
                  key: db-service
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef: # ConfigMap
                  name: db-configmap
                  key: db-database
            - name: DB_USER
              valueFrom:
                secretKeyRef: # Secret
                  name: db-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: # Secret
                  name: db-secrets
                  key: db-user-password
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 500m
