apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
spec:
  limits:
    - type: Container
      min:
        cpu: 100m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
