apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
spec:
  limits:
    - default:
        cpu: 1
        memory: 250Mi
      defaultRequest:
        cpu: 0.5
        memory: 100Mi
      max:
        cpu: 2
        memory: "1024Mi"
      min:
        cpu: 0.5
        memory: 100Mi
      type: Container
